/* 
 * DaDaPush Public API
 *
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.DaDaPush.Client.Api;
using Com.DaDaPush.Client.Model;
using Com.DaDaPush.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.DaDaPush.Client.Test
{
    /// <summary>
    ///  Class for testing MessagePushResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessagePushResponseTests
    {
        // TODO uncomment below to declare an instance variable for MessagePushResponse
        //private MessagePushResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessagePushResponse
            //instance = new MessagePushResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessagePushResponse
        /// </summary>
        [Test]
        public void MessagePushResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MessagePushResponse
            //Assert.IsInstanceOf(typeof(MessagePushResponse), instance);
        }


        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Test]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }

    }

}
