/* 
 * DaDaPush Public API
 *
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.DaDaPush.Client.Api;
using Com.DaDaPush.Client.Model;
using Com.DaDaPush.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.DaDaPush.Client.Test
{
    /// <summary>
    ///  Class for testing PageResponseOfMessageObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PageResponseOfMessageObjectTests
    {
        // TODO uncomment below to declare an instance variable for PageResponseOfMessageObject
        //private PageResponseOfMessageObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PageResponseOfMessageObject
            //instance = new PageResponseOfMessageObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PageResponseOfMessageObject
        /// </summary>
        [Test]
        public void PageResponseOfMessageObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PageResponseOfMessageObject
            //Assert.IsInstanceOf(typeof(PageResponseOfMessageObject), instance);
        }


        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'TotalElements'
        /// </summary>
        [Test]
        public void TotalElementsTest()
        {
            // TODO unit test for the property 'TotalElements'
        }
        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Test]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }

    }

}
