/* 
 * DaDaPush Public API
 *
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.DaDaPush.Client.Api;
using Com.DaDaPush.Client.Model;
using Com.DaDaPush.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.DaDaPush.Client.Test
{
    /// <summary>
    ///  Class for testing ResultOfPageResponseOfMessageObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResultOfPageResponseOfMessageObjectTests
    {
        // TODO uncomment below to declare an instance variable for ResultOfPageResponseOfMessageObject
        //private ResultOfPageResponseOfMessageObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResultOfPageResponseOfMessageObject
            //instance = new ResultOfPageResponseOfMessageObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResultOfPageResponseOfMessageObject
        /// </summary>
        [Test]
        public void ResultOfPageResponseOfMessageObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ResultOfPageResponseOfMessageObject
            //Assert.IsInstanceOf(typeof(ResultOfPageResponseOfMessageObject), instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Errmsg'
        /// </summary>
        [Test]
        public void ErrmsgTest()
        {
            // TODO unit test for the property 'Errmsg'
        }

    }

}
